services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    restart: always

  fake_store_api:
    container_name: fake_store_api
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=ilia
    depends_on:
      - mongodb
    restart: always

  fake_store:
    container_name: fake_store
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - API_URL=http://fake_store_api:8000
    depends_on:
      - fake_store_api
    restart: always
