services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    restart: always

  fake_store_api:
    container_name: fake_store_api
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=ilia
    depends_on:
      - mongodb
    restart: always
